- collaboration/README.md
> Update Collaboration README.md

- collaboration/learning_goals.md
Create a small intro and learning goals in the collaboration/learning_goals.md
> Added intro and learning goals to learning_goals.md

- collaboration/learning_goals.md
Add a new individual learning goal
> Add Learning goal

- README.md
Created the main README.md file detailing what our group repository is all about.
> Create the main README.md file

- .vscode/settings.json
- solutions/tests/README.md
Added a structured document defining testing standards, guidelines, and procedures for the project.  
To ensure consistency in how tests are written, maintained, and executed across the team.  
- Document includes testing categories (Unit, Integration, Functional, E2E).  
- Added detailed running instructions for pytest and unittest.  
- Integrated mock examples for better isolation of tests.
> Structured Test Solution and Key Testing Standards

- collaboration/learning_goals.md
added a description to the file and wrote the collective learning goals. added and formatted the individual learning goals that were sent on slack.
> finalizing learning_goals README

- collaboration/learning_goals.md
Updated the collective learning goals. And created a template with the group members names to use it to add their individual learning goals. And kept the individual learning goals which were already added before this PR and assigned them to their respective members.
> refining the file and creating a template to add individual goals

- collaboration/learning_goals.md
I have included my individual learning goals in the file learning_goals.md within this branch.
> Update learning goals

- collaboration/constraints.md
Added project constraints to define external and internal factors impacting our progress.
> Project Constraints

- collaboration/learning_goals.md
> Anas Ziadah's goals

- CONTRIBUTING.md
Adding a CONTRIBUTING section to the repo and allowing the team to push their parts.
> Contributing readme

- solutions/README.md
Added the calc_avg.py in the solutions summary table in the solutions README.md file to document the contribution.
> Add calc_avg.py in the solutions README

- CONTRIBUTING.md
- collaboration/learning_goals.md
I add my part in this section.
> Updating Contributive 

- collaboration/learning_goals.md
> UPDATE - learning goals

- solutions/README.md
- solutions/euler_totient.py
- solutions/tests/test_euler_totient.py
The Euler's Totient function (ϕ(n)) counts the number of integers between 1 and n that are coprime with n. Two numbers are considered coprime if their greatest common divisor (GCD) equals 1. The function has applications in number theory and cryptography.
This pull request adds the implementation of the Euler Totient function, including docstrings with examples and unit tests. The euler_totient function computes the value of Euler's Totient function for a given integer n, and the implementation runs in O(√n) time complexity.
Added a function euler_totient(n) to calculate Euler's Totient function.
Included docstrings with example usage.
Created unit tests to validate the implementation for various cases, including edge cases and invalid inputs.
Prime numbers.
Composite numbers.
The case …
> Add Euler's Totient Function Implementation

- .vscode/settings.json
- collaboration/learning_goals.md
> Add Faisal's Learning Goals

- solutions/grading_system.py
- solutions/tests/test_grading_system.py
implement a solution for the issue #42
> adding the solution of the Grading System challenge to the repo

- solutions/euler_totient.py
euler totient fix CI errors
close  #73
> Euler totient CI fix

- collaboration/communication.md
I am setting the communication.md file so that others can share the availability.
> Communication markdown Set up

- collaboration/communication.md
Added my availability hours to the communictaion.md file
> Mohamed's availability

- solutions/simple_calculator.py
- solutions/tests/test_simple_claculator.py
> solution for the simple calculator challenge

- collaboration/constraints.md
Updating the deadlines in the constraints.md file according to the extension made for the second CS deliverable.
> Updating deadlines in the Constrains.md file

- solutions/README.md
I have added my reviewed and merged solution for the grading system based on numeric scores to the README file in the solution folder.
> Adding my reviewed solution grading system to the solution.md file

- CONTRIBUTING.md
Added the setup and cloning parts to the md file. Also, I enhanced the file a little bit (changing some statements).
> Finalize the contributing file

- solutions/grading_system.py
> Fix CI check related to grading_system.py

- CONTRIBUTING.md
- collaboration/communication.md
- solutions/grading_system.py
> Anas communication

- solutions/README.md
- solutions/kronecker_product.py
- solutions/tests/test_kronecker_product.py
A function kronecker_product(matrix_a, matrix_b) that computes the Kronecker product.
Input validation to ensure both arguments are 2D lists.
A set of test cases to verify functionality with valid matrices, identity matrices, zero matrices, and invalid inputs.
The function does not rely on any external libraries and uses basic Python list operations to compute the Kronecker product.
The code has been tested with multiple edge cases, including square and non-square matrices, identity matrices, and zero matrices.
Tests ensure correct handling of invalid inputs.
The implementation is kept simple with no dependencies outside of Python's standard library.
closes #97
> Implement Kronecker Product Function

- solutions/greatest_number.py
- solutions/tests/test_greatest_number.py
Implement  a solution for the issue #58
> Greatest number challenge

- solutions/feet_to_meters.py
- solutions/tests/test_feet_to_meters.py
> Feet to meters

- solutions/README.md
- solutions/feet_to_meters.py
> Update feet to meters

- solutions/README.md
- solutions/direction_to_degree.py
- solutions/tests/test_direction_to_degree.py
> Direction to degree

- solutions/README.md
- solutions/tests/test_volts_to_amperes.py
- solutions/volts_to_amperes.py
> Volts to amperes

- collaboration/learning_goals.md
> ozgur times

- solutions/README.md
adding my second solution name to the table in the README.md file in the solution folder
> adding my solution file name

- solutions/greatest_number.py
I modified some parts of the docstring to align with the issue description.
> refine the docstring of the function

- collaboration/learning_goals.md
- solutions/check_prime_number.py
- solutions/tests/test_check_prime_number.py
> Check prime number solution and test

- solutions/README.md
> solution readme update

- notes/README.md
Added documentation for the notes directory.
> Notes readme

- collaboration/communication.md
> fix CI in communication.md

- solutions/README.md
- solutions/tests/test_password_strength.py
> Solutionnew

- collaboration/communication.md
- collaboration/learning_goals.md
**Fix collaboration conflict and add my part to collaboration folder**
> Contributing update

- solutions/tests/test_direction_to_degree.py
> fix bug in test_direction_to_degree

- solutions/tests/test_feet_to_meters.py
**Fix bug and update the test file**
---
---
> Fix feet to meters

- solutions/tests/test_miles_to_kilometers.py
Fix bug and update the test file
---
---
> Fix mile to kilometers

- solutions/tests/test_volts_to_amperes.py
**Fix bug and update the test file**
---
---
> Fix volts to amperes

- collaboration/retrospective.md
The document includes a detailed reflection on the team's performance, highlighting successes, challenges, and lessons learned from the project.
> This is the project retrospective

- solutions/README.md
- solutions/gcd.py
- solutions/tests/test_gcd.py
Changes:
`gcd.py`:
Implements the gcd(a, b) function to calculate the greatest common divisor using the Euclidean algorithm.
Includes detailed docstrings with examples, parameters, and return values.
`test_gcd.py`:
Adds unit tests for the gcd function.
Covers valid inputs (positive, negative, zero), edge cases, and invalid inputs (non-integer types).
> Added GCD Calculator Challenge

- collaboration/retrospective.md
Update some points in the file  to be more clear
> Modify some points in the retrospective  file

- solutions/direction_to_degree.py
- solutions/feet_to_meters.py
- solutions/miles_to_kilometers.py
- solutions/volts_to_amperes.py
**Fix the header of the code files for more clarity** 
---
---
> fix codes files

- notes/README.md
Adding the learning resources I used during the project period
> Adding my learning resources

- solutions/README.md
- solutions/count_character.py
- solutions/tests/test_count_character.py
> add solution to Count Character challenge and updated README
